SYSTEM_DESIGN_PROBLEMS = [
    {
        "week": 1,
        "title": "URL Shortener",
        "example": "bit.ly, TinyURL",
        "prompt": "Design a service that takes a long URL and returns a short one. Users can visit the short URL and get redirected.",
        "think_about": [
            "How do you generate the short code — random, hash, or counter-based?",
            "Where do you store the mapping?",
            "How do you handle 301 vs 302 redirects and why does it matter?",
            "What happens when the same long URL is submitted twice?",
        ],
        "scale_nudge": "100M URLs created per day. How does your storage estimate change?",
    },
    {
        "week": 2,
        "title": "Rate Limiter",
        "example": "API gateway throttling, login attempt limits",
        "prompt": "Design a rate limiter that allows a user a maximum of N requests per minute. Requests over the limit get rejected.",
        "think_about": [
            "Fixed window vs sliding window vs token bucket — what are the tradeoffs?",
            "Where does the rate limiter live — client, server, or middleware?",
            "How do you handle distributed servers — where is the shared state?",
            "What data structure holds the request counts?",
        ],
        "scale_nudge": "Your service has 50 servers behind a load balancer. How does that change your design?",
    },
    {
        "week": 3,
        "title": "Pastebin",
        "example": "pastebin.com, GitHub Gist",
        "prompt": "Design a service where users paste text and get a unique URL to share it. Pastes can optionally expire.",
        "think_about": [
            "How do you generate unique IDs for each paste?",
            "SQL vs NoSQL — which fits better and why?",
            "How do you implement expiry — TTL in the DB, a cleanup job, or lazy deletion?",
            "What if a paste goes viral — how do you handle read spikes?",
        ],
        "scale_nudge": "10M pastes per day, average 10KB each. Estimate storage for one year.",
    },
    {
        "week": 4,
        "title": "Design Twitter Feed",
        "example": "Twitter home timeline, Instagram feed",
        "prompt": "Design the home feed for a social app — users see posts from people they follow, in reverse chronological order.",
        "think_about": [
            "Push vs pull model for feed generation — when does each win?",
            "How do you handle celebrities with 10M followers — fanout on write breaks down?",
            "Where do you cache feeds and how do you invalidate?",
            "How do you paginate efficiently without missing or duplicating posts?",
        ],
        "scale_nudge": "A user follows 500 people. Each posts once a day. How many writes does fanout-on-write generate across all users?",
    },
    {
        "week": 5,
        "title": "Notification Service",
        "example": "Push notifications, email alerts, SMS",
        "prompt": "Design a system that sends notifications to users across multiple channels — push, email, and SMS.",
        "think_about": [
            "How do you decouple the notification trigger from the actual send?",
            "What queue or message broker sits in between?",
            "How do you handle failures — retries, dead letter queues?",
            "How do you respect user preferences (opted out of email, only push)?",
        ],
        "scale_nudge": "1M notifications per hour at peak. How do you scale the workers?",
    },
    {
        "week": 6,
        "title": "Key-Value Store",
        "example": "Redis, DynamoDB, Memcached",
        "prompt": "Design a distributed key-value store that supports get, put, and delete. It should be fast and fault-tolerant.",
        "think_about": [
            "How do you partition data across nodes — consistent hashing?",
            "What happens when a node goes down — how do reads and writes continue?",
            "Consistency vs availability — where do you land on the CAP tradeoff?",
            "How do you handle replication lag?",
        ],
        "scale_nudge": "You need 99.99% uptime. How many replicas do you need and where do you place them?",
    },
    {
        "week": 7,
        "title": "Web Crawler",
        "example": "Googlebot, Common Crawl",
        "prompt": "Design a web crawler that starts from a seed URL, fetches pages, extracts links, and crawls those too.",
        "think_about": [
            "How do you avoid crawling the same URL twice — what data structure?",
            "How do you prioritize which URLs to crawl next?",
            "How do you respect robots.txt and crawl rate limits?",
            "How do you parallelize crawling across many workers?",
        ],
        "scale_nudge": "1 billion pages to crawl, average 500KB per page. Estimate bandwidth and storage.",
    },
    {
        "week": 8,
        "title": "Ride-Sharing Location Service",
        "example": "Uber/Lyft driver location tracking",
        "prompt": "Design the backend for tracking driver locations in real time and matching nearby drivers to riders.",
        "think_about": [
            "How do drivers report their location — polling or WebSocket?",
            "How do you query drivers within X km of a rider efficiently?",
            "What data structure or DB feature handles geospatial queries?",
            "How do you handle location data that goes stale?",
        ],
        "scale_nudge": "1M active drivers updating location every 5 seconds. How many writes per second is that?",
    },
    {
        "week": 9,
        "title": "Distributed Message Queue",
        "example": "Kafka, SQS, RabbitMQ",
        "prompt": "Design a message queue where producers push messages and consumers pull them. Messages should be durable and delivered at least once.",
        "think_about": [
            "How do you persist messages so they survive a server restart?",
            "How do you handle multiple consumers for the same queue — competing consumers vs fan-out?",
            "How do you guarantee at-least-once delivery without infinite redelivery?",
            "How do you handle a slow consumer that falls behind?",
        ],
        "scale_nudge": "Messages must be retained for 7 days. Average message is 1KB, 1M messages/day. Estimate storage.",
    },
    {
        "week": 10,
        "title": "Search Autocomplete",
        "example": "Google search bar suggestions, e-commerce search",
        "prompt": "Design the autocomplete system that shows query suggestions as the user types, updated in real time.",
        "think_about": [
            "What data structure powers prefix matching — trie, inverted index?",
            "How do you rank suggestions — by frequency, recency, personalization?",
            "How do you keep suggestions fresh without recomputing everything constantly?",
            "Where do you cache — browser, CDN, backend?",
        ],
        "scale_nudge": "Each keystroke is a request. A user types a 10-character query. How many API calls is that, multiplied by 10M users?",
    },
    {
        "week": 11,
        "title": "File Storage Service",
        "example": "Dropbox, Google Drive",
        "prompt": "Design a service where users upload files, which sync across their devices and can be shared with others.",
        "think_about": [
            "How do you avoid re-uploading chunks that haven't changed — chunking and deduplication?",
            "Where do you store metadata vs file content?",
            "How do you sync across devices — polling, long-polling, or WebSocket?",
            "How do you handle concurrent edits to the same file?",
        ],
        "scale_nudge": "Average file is 2MB, 50M users each storing 5GB. Estimate total storage.",
    },
    {
        "week": 12,
        "title": "Video Streaming Service",
        "example": "YouTube, Netflix",
        "prompt": "Design a platform where users upload videos that get processed and streamed to viewers at different quality levels.",
        "think_about": [
            "How do you transcode a video into multiple resolutions after upload?",
            "What is adaptive bitrate streaming and how does the client pick quality?",
            "Where does a CDN fit and how does it reduce load on your origin servers?",
            "How do you handle a video that suddenly goes viral?",
        ],
        "scale_nudge": "500 hours of video uploaded every minute (YouTube's real stat). How do you scale transcoding?",
    },
]
